[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Portal da TransparÃªncia"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]
